export default async (req, res) => {
  const userData = {
    userName: "Tauranga",
    profilePic: "https://randomuser.me/api/portraits/women/18.jpg",
    dateJoined: new Date('March 12, 2022'),
    areFollowing: true,
    numFollowers: 15,
    numFollowing: 38,
    numPosts: 9,
    posts: [
      {
        userName: "Tauranga",
        profilePic: "https://randomuser.me/api/portraits/women/18.jpg",
        userId: 4186453486,
        timePosted: new Date('March 15, 2022'),
        typePost: "1",
        originalPost: "I don't know where I need to go to get the new Pokemon",
        originalUser: null,
        originalTime: null,
        quote: null,
      },
      {
        userName: "Tauranga",
        profilePic: "https://randomuser.me/api/portraits/women/18.jpg",
        userId: 8464268426,
        timePosted: new Date('March 18, 2022'),
        typePost: "3",
        originalPost: "I don't know where I need to go to get the new Pokemon",
        originalUser: 'Tauranga',
        originalTime: new Date('March 15, 2022'),
        quote: 'Reposting to you all see',
      },
      {
        userName: "Tauranga",
        profilePic: "https://randomuser.me/api/portraits/women/18.jpg",
        userId: 8464268426,
        timePosted: new Date('March 18, 2022'),
        typePost: "3",
        originalPost: "I don't know where I need to go to get the new Pokemon",
        originalUser: 'Tauranga',
        originalTime: new Date('March 15, 2022'),
        quote: null,
      },
      {
        userName: "Tauranga",
        profilePic: "https://randomuser.me/api/portraits/women/18.jpg",
        userId: 4186453486,
        timePosted: new Date('March 15, 2022'),
        typePost: "1",
        originalPost: "I don't know where I need to go to get the new Pokemon",
        originalUser: null,
        originalTime: null,
        quote: null,
      },
      {
        userName: "Tauranga",
        profilePic: "https://randomuser.me/api/portraits/women/18.jpg",
        userId: 8464268426,
        timePosted: new Date('March 18, 2022'),
        typePost: "3",
        originalPost: "I don't know where I need to go to get the new Pokemon",
        originalUser: 'Tauranga',
        originalTime: new Date('March 15, 2022'),
        quote: 'Reposting to you all see',
      },
      {
        userName: "Tauranga",
        profilePic: "https://randomuser.me/api/portraits/women/18.jpg",
        userId: 8464268426,
        timePosted: new Date('March 18, 2022'),
        typePost: "3",
        originalPost: "I don't know where I need to go to get the new Pokemon",
        originalUser: 'Tauranga',
        originalTime: new Date('March 15, 2022'),
        quote: null,
      },
      {
        userName: "Tauranga",
        profilePic: "https://randomuser.me/api/portraits/women/18.jpg",
        userId: 4186453486,
        timePosted: new Date('March 15, 2022'),
        typePost: "1",
        originalPost: "I don't know where I need to go to get the new Pokemon",
        originalUser: null,
        originalTime: null,
        quote: null,
      },
      {
        userName: "Tauranga",
        profilePic: "https://randomuser.me/api/portraits/women/18.jpg",
        userId: 8464268426,
        timePosted: new Date('March 18, 2022'),
        typePost: "3",
        originalPost: "I don't know where I need to go to get the new Pokemon",
        originalUser: 'Tauranga',
        originalTime: new Date('March 15, 2022'),
        quote: 'Reposting to you all see',
      },
      {
        userName: "Tauranga",
        profilePic: "https://randomuser.me/api/portraits/women/18.jpg",
        userId: 8464268426,
        timePosted: new Date('March 18, 2022'),
        typePost: "3",
        originalPost: "I don't know where I need to go to get the new Pokemon",
        originalUser: 'Tauranga',
        originalTime: new Date('March 15, 2022'),
        quote: null,
      },
    ]
  }

  res.json(userData)
}